# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homee',
            name='contact_no',
        ),
    ]
