# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_homee_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('service_area', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homee',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homee',
            name='firstname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homee',
            name='lastname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homee',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
